# Task : You are a give a customer list that's responses from customers. Clean it and submit a clean list of all customers to be called.

In [ ]:
import pandas as pd

df = pd.read_excel('CustomerCallList.xlsx')

In [4]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

# Step 1. Remove any duplicates

In [6]:
df.drop_duplicates()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

# Step 2. Remove any unwanted columns like the Not_Useful_Column

In [18]:
df = df.drop(columns = ['Not_Useful_Column'])

In [19]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

# Step 3. Start cleaning column by column
# Clean the last_name column to remove the /,...

In [31]:
df['Last_Name'] = df['Last_Name'].str.strip('123./')

In [32]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

# Step 3. Clean the Phone_number column

In [39]:
df["Phone_Number"] = df["Phone_Number"].str.replace("[^a-zA-Z0-9]","")

In [40]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,NaN,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,NaN,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,NaN,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [65]:
df['Phone_Number'] = df['Phone_Number'].str.replace(r"[^a-zA-Z0-9]", "-", regex=True)

In [66]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123---------,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123---------,93 West Main Street,No,Yes
2,1003,Walter,White,nan---------,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123---------,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876---------,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304---------,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,nan---------,1209 South Street,No,No
7,1008,Sherlock,Holmes,876---------,98 Clue Drive,N,No
8,1009,Gandalf,NaN,Na----------,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123---------,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,nan---------,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,nan---------,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123---------,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876---------,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304---------,214 HR Avenue,N,No
15,1016,Ron,Weasley,123---------,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123---------,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,nan---------,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,Na----------,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876---------,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,Skywalker,876---------,"910 Tatooine Road, Tatooine",Yes,N

In [69]:

df = pd.read_excel('CustomerCallList.xlsx')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [70]:
df['Phone_Number'] = df['Phone_Number'].str.replace(r"[^a-zA-Z0-9]", "-", regex=True)

In [71]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,NaN,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N-a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,NaN,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,NaN,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N-a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True

# Step =6 Remove the NaN and N-a from the phone numbers

In [77]:
#df['Phone_Number'] = df['Phone_Number'].str.replace('NaN','')

df['Phone_Number'] = df['Phone_Number'].fillna('')  # To remove the Not a number (NaN)


df['Phone_Number'] = df['Phone_Number'].str.replace('N-a','')  # Use this replace the N-a characters (
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True

# Step 7. Modify the address column

In [82]:
df[['Street_Address','State','Zip_Code']] = df['Address'].str.split(',',expand=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,False,93 West Main Street,None,None
2,1003,Walter,/White,,298 Drugs Driveway,N,NaN,True,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,No,No,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,False,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,True,612 Shire Lane,Shire,None
11,1012,Harry,...Potter,,2394 Hogwarts Avenue,Y,NaN,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,False,343 City Parkway,None,None
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,False,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,True,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,N/a,Yes,True,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,Tatooine,None

In [95]:

# Now drop the address column 
#df.drop(columns=['Address'], inplace=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,No,Yes,93 West Main Street,None,None
2,1003,Walter,/White,,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,...Potter,,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson_,304-762-2467,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,None

In [88]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Not_Useful_Column,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Yes,No,True,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,No,Yes,False,93 West Main Street,None,None
2,1003,Walter,/White,,N,NaN,True,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,Yes,Y,True,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,No,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,Yes,Yes,True,768 City Parkway,None,None
6,1007,Jeff,Winger,,No,No,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,N,No,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Yes,NaN,False,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,Yes,No,True,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Yes,No,True,612 Shire Lane,Shire,None
11,1012,Harry,...Potter,,Y,NaN,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,Yes,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,Yes,No,False,343 City Parkway,None,None
14,1015,Toby,Flenderson_,304-762-2467,N,No,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,No,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,Yes,No,False,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,Y,NaN,True,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,Yes,True,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,True,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876-678-3469,Yes,N,True,910 Tatooine Road,Tatooine,None

In [91]:
df = df.drop(columns = ['Not_Useful_Column'])

In [92]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,No,Yes,93 West Main Street,None,None
2,1003,Walter,/White,,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,...Potter,,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson_,304-762-2467,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,None

# Step 8: Modify the do not contact column and the paying customer column to give only Y and N responses

In [96]:
df['Do_Not_Contact'] = df['Do_Not_Contact'].str.replace('Yes','Y')

In [97]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,No,Y,93 West Main Street,None,None
2,1003,Walter,/White,,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,Yes,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,...Potter,,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson_,304-762-2467,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,Y,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,None

In [98]:
df['Do_Not_Contact'] = df['Do_Not_Contact'].str.replace('No','N')

In [99]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Yes,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,No,Y,93 West Main Street,None,None
2,1003,Walter,/White,,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,Yes,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,,No,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,Yes,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Yes,N,612 Shire Lane,Shire,None
11,1012,Harry,...Potter,,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,Yes,N,343 City Parkway,None,None
14,1015,Toby,Flenderson_,304-762-2467,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,Yes,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,Y,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,None

In [100]:
df['Paying Customer'] = df['Paying Customer'].str.replace('Yes','Y')

In [101]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,No,Y,93 West Main Street,None,None
2,1003,Walter,/White,,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,,No,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,None
11,1012,Harry,...Potter,,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson_,304-762-2467,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,Y,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,None

In [102]:
df['Paying Customer'] = df['Paying Customer'].str.replace('No','N')

In [103]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,N,Y,93 West Main Street,None,None
2,1003,Walter,/White,,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,None
11,1012,Harry,...Potter,,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson_,304-762-2467,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,Y,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,None

# Step 9. Clean the entire Dataframe to remove the None digit characters

In [106]:
df = df.replace('N/a','')

In [105]:
df.replace('NaN','')

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,N,Y,93 West Main Street,None,None
2,1003,Walter,/White,,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,None
11,1012,Harry,...Potter,,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson_,304-762-2467,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,Y,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,None

In [107]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,N,Y,93 West Main Street,None,None
2,1003,Walter,/White,,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,None
11,1012,Harry,...Potter,,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson_,304-762-2467,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,,Y,,None,None
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,None
20,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,None

In [108]:
df = df.fillna('')

In [109]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123-643-9775,N,Y,93 West Main Street,,
2,1003,Walter,/White,,N,,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-2345,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,
5,1006,Ron,Swanson,304-762-2467,Y,Y,768 City Parkway,,
6,1007,Jeff,Winger,,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,
8,1009,Gandalf,,,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,
11,1012,Harry,...Potter,,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson_,304-762-2467,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,,Y,,3498 Super Lane,,
18,1019,Creed,Braton,,,Y,,,
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,
20,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,

# Step 10. Filter the customers to be called based on the Do not contact

In [111]:
for x in df.index:
    if df.loc[x,'Do_Not_Contact'] == 'Y':
        df.drop(x, inplace=True)

df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,
2,1003,Walter,/White,,N,,298 Drugs Driveway,,
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,
6,1007,Jeff,Winger,,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,
8,1009,Gandalf,,,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,
11,1012,Harry,...Potter,,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson_,304-762-2467,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,,Y,,3498 Super Lane,,
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,
20,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,

# step 11 Remove blank phone numbers

In [114]:
for x in df.index:
    if df.loc[x,'Phone_Number'] == '':
        df.drop(x, inplace=True)

df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson_,304-762-2467,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,
20,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,

# Step 12. Reset the index

In [115]:
df= df.reset_index(drop=True)

In [116]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,
1,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,
2,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,
3,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,
4,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,
5,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,
6,1015,Toby,Flenderson_,304-762-2467,N,N,214 HR Avenue,,
7,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,
8,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,
9,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,
10,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,

# Step 13 Save the new cleaned data

In [118]:
df.to_excel('CleanedCustomerList.xlsx')

In [119]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,
1,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,
2,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,
3,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,
4,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,
5,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,
6,1015,Toby,Flenderson_,304-762-2467,N,N,214 HR Avenue,,
7,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,
8,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,
9,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,
10,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,